../design/core/pkg.sv
../design/tracer/pkg.sv
../design/tracer/tracer_pkg.sv
../design/tracer/tracer.sv
../design/core/adder.v
../design/core/ALU.v
../design/core/pcregister.v
../design/core/ALUControl.v
../design/core/control_unit.v
../design/core/forwarding_unit.v
../design/core/hazard_detection_unit.v
../design/core/Imm_Gen.v
../design/core/Instruction_reg.sv
../design/core/load_unit.v
../design/core/store_unit.v
../design/core/mem_ntv_interface_if.sv
../design/core/mux_3x1.v
../design/core/mux_18.v
../design/core/mux.v
../design/core/register_en.v
../design/core/register_file.v
../design/core/register.v
../design/core/RISCV32I.sv
./memory/mem.v
../design/soc/soc_top.sv
testbench.v